SMF to support SDM Subscription and Unsubscription for UE Session
free5gc/smf pull request #123
Opened 2024-09-14 16:39 UTC by saileshvvr

Add support for SDM Subscription during UE 1st PDU Session Establishment
Add support for SDM UnSubscription during release of last UE PDU Session

2024-09-19 08:52 UTC, ianchen0119 commented
@andy89923 
Please help to test the functionality (w/ OAuth and w/o OAuth)

2024-09-20 13:51 UTC, andy89923 commented on internal/sbi/consumer/udm_service.go
> +			client = Nudm_SubscriberDataManagement.NewAPIClient(SDMConf)
`getSubscribeDataManagementClient()`

2024-09-20 13:51 UTC, andy89923 commented on internal/sbi/consumer/udm_service.go
> +				client = Nudm_SubscriberDataManagement.NewAPIClient(SDMConf)
`getSubscribeDataManagementClient()`

2024-09-20 16:29 UTC, saileshvvr commented on internal/sbi/consumer/udm_service.go
> +			client = Nudm_SubscriberDataManagement.NewAPIClient(SDMConf)
done!

2024-09-20 16:29 UTC, saileshvvr commented on internal/sbi/consumer/udm_service.go
> +				client = Nudm_SubscriberDataManagement.NewAPIClient(SDMConf)
done!

2024-09-20 16:30 UTC, saileshvvr commented
Hi @andy89923 , 
Addressed the comment. I did not follow the refactored code and used the legacy way.
Updated as suggested :) 
Thanks!

2024-09-29 17:38 UTC, saileshvvr commented
Hi @andy89923 
Can you please share if in case anything missing.
As this PR functionality is pending from quite sometime, would like to check once!
Thanks

2024-09-30 03:57 UTC, andy89923 approved these changes
@saileshvvr Sorry for the late review! 

After testing w/wo OAuth, this PR can subscribe when a new UE and unsubscribe when the UE's last PDU session is released.  

Thanks for the PR, LGTM!

2024-09-30 05:12 UTC, ianchen0119 requested changes

2024-09-30 05:12 UTC, ianchen0119 commented on internal/sbi/processor/pdu_session.go
> +	if !p.Context().Ues.UeExists(smContext.Supi) {
What if the error happens after the SDM data changed?
I think use the `defer` would be better in this case:
```go
defer func(err error) {
  if err != nil {
	if !p.Context().Ues.UeExists(smContext.Supi) {
		if problemDetails, err := p.Consumer().
			Subscribe(ctx, smContext, smPlmnID); problemDetails != nil {
			smContext.Log.Errorln("SDM Subscription Failed Problem:", problemDetails)
		} else if err != nil {
			smContext.Log.Errorln("SDM Subscription Error:", err)
		}
	} else {
		p.Context().Ues.IncrementPduSessionCount(smContext.Supi)
	}
  }
}(err)
```

2024-09-30 05:12 UTC, ianchen0119 commented on internal/sbi/processor/pdu_session.go
> +	if p.Context().Ues.UeExists(smContext.Supi) {
Same as above.
Please do this action by using `defer`.

2024-09-30 05:12 UTC, ianchen0119 commented on internal/sbi/processor/pdu_session.go
> +	if p.Context().Ues.UeExists(smContext.Supi) {
Same as above.
Please do this action by using `defer`.

2024-09-30 05:12 UTC, ianchen0119 commented on internal/sbi/processor/pdu_session.go
> +			if smf_context.GetSelf().Ues.UeExists(smContext.Supi) {
Same as above.
Please do this action by using `defer`.

2024-09-30 05:14 UTC, ianchen0119 commented
It looks good to me except the requested changes.

Hi @saileshvvr 
Please help to update & test the PR based on my comments.
Many thanks!

2024-10-06 06:27 UTC, saileshvvr commented
Hi @ianchen0119 ,

Thank you for the feedback. As I was occupied with other work, missed the comments.
I shall check and update accordingly.

Thanks!

2024-10-06 06:37 UTC, andy89923 commented
Hi @saileshvvr ,

We can't use the defer function and pass the error to differentiate if the error happens after the defer function. 
Should creat an error instead.
```go
func main() {
	var err error
	defer func() {
		if err != nil {
			fmt.Printf("defer: %s\n", err)
		} else {
			fmt.Println("defer: defer not error")
		}
	}()

	err = errors.New("new error 1")
	if err != nil {
		return
	}
}

/*output
defer: new error 1
*/
```
You can refer to https://stackoverflow.com/questions/42703707/when-defer-func-evaluates-its-parameters

2024-10-06 07:50 UTC, saileshvvr commented
Hi @andy89923 , @ianchen0119 ,
Agree with your comments. Can we handle this as a seperate improvement PR once after delivering this implementation.
After submitting this PR I shall raise a new improvement PR with the recommended changes if you are OKAY.
please share your comments. Thanks!

2024-10-06 08:23 UTC, andy89923 commented
Hi @saileshvvr ,

> Can we handle this as a separate improvement PR? 

No, we should revise this in the same PR. 

If you don't have time, I will help revise if the PR isn't ready until next Wednesday.

2024-10-06 08:41 UTC, saileshvvr commented
Thank you @andy89923 . 
As I shared earlier, I was occupied with other tasks and may be getting time during next week.
Thanks for your quick response and support.

2024-10-23 13:52 UTC, andy89923 commented
Hi @saileshvvr ,

Sorry, I don't have time to help with this PR; please fix the comments when you are free!

2024-10-24 11:37 UTC, saileshvvr commented
Hi @ianchen0119 , @andy89923 ,
As I understand we can keep the code with in defer{}() only during Subscribe(). 

For all other cases (Session Release(UE/NW triggered) or Local Release or Failure cases) we can just call Unsubscribe(). As Unsubscribe() will decrement the session count if more than 1 session else session HTTP DELETE to Unsubscribe.
So no change may be needed during Unsubscribe() call.

Please let me know your comments so as to update the latest patch accordingly.

Thanks
Sailesh

2024-10-29 03:50 UTC, saileshvvr commented
Thanks @ianchen0119 @andy89923

2024-10-29 15:43 UTC, ianchen0119 approved these changes

2024-10-29 15:43 UTC, merged